In [26]:
import pandas as pd
import numpy as np
import joblib

In [2]:
true_news=pd.read_csv('True.csv')
true_news

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [3]:
true_news.drop('date',axis=1,inplace=True)

In [4]:
true_news.isnull().sum()

title      0
text       0
subject    0
dtype: int64

In [5]:
fake_news=pd.read_csv('Fake.csv')
fake_news

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [6]:
fake_news.drop('date',axis=1,inplace=True)

In [7]:
fake_news.isnull().sum()

title      0
text       0
subject    0
dtype: int64

In [8]:
fake_news['label']=0
true_news['label']=1
df=pd.concat([fake_news,true_news],axis=0)
df = df.sample(frac=1).reset_index(drop=True)

In [9]:
df.to_csv("news_dataset.csv", index=False)
df=pd.read_csv('news_dataset.csv')
df

,title,text,subject,label
0,House Republicans Forcing Fetal Tissue Resear...,Using the long-debunked Planned Parenthood vid...,News,0
1,BREAKING: Donald Trump Walked Into Dressing R...,Not only is Donald Trump an admitted serial gr...,News,0
2,"Turkish capital bans LGBT cinema, exhibitions",ISTANBUL (Reuters) - The Turkish capital Ankar...,worldnews,1
3,Kuwait orders North Korea's ambassador to leav...,KUWAIT (Reuters) - Kuwait has ordered North Ko...,worldnews,1
4,Sudan disappointed at renewal of U.S. travel b...,KHARTOUM (Reuters) - Sudan’s foreign ministry ...,politicsNews,1
...,...,...,...,...
44893,Canada foreign minister will oppose U.S. borde...,WASHINGTON (Reuters) - Canada opposes the idea...,politicsNews,1
44894,LISTEN TO THIS MEMBER OF CONGRESS WHINE ABOUT ...,He wants more money? He should find a differen...,politics,0
44895,"Republicans Rubio, Cruz release taxes, piling ...",WASHINGTON (Reuters) - Republican presidential...,politicsNews,1
44896,WATCH: Fox Business Misses The Days Of Child ...,Many new minimum wage increases took effect on...,News,0
44897,OBAMA’S GAL PAL Loretta Lynch WON’T RECUSE HER...,Reasonable Americans expected never expected u...,left-news,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   label    44898 non-null  int64
dtypes: int64(1), object(3)
memory usage: 1.4+ MB

In [11]:
df.describe()

              label
count  44898.000000
mean       0.477015
std        0.499477
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        1.000000

In [12]:
#!pip install nltk

In [13]:
#!pip show nltk

In [14]:
import nltk

In [15]:
from nltk.corpus import stopwords

In [16]:
stop_words=stopwords.words('english')
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [17]:
import re
#from nltk.stem import PorterStemmer
#stemmer=PorterStemmer()
def formatted_text(text):
      clean_text=re.sub(r'[^a-zA-Z]',' ',text)
      words=clean_text.lower().split()
      words=[word for word in words if word not in stop_words]
      return ' '.join(words)
df['formatted_text']=df['text'].apply(formatted_text)

In [29]:
df.drop('text',axis=1)

,title,subject,label,formatted_text
0,House Republicans Forcing Fetal Tissue Resear...,News,0,using long debunked planned parenthood videos ...
1,BREAKING: Donald Trump Walked Into Dressing R...,News,0,donald trump admitted serial groper adulterer ...
2,"Turkish capital bans LGBT cinema, exhibitions",worldnews,1,istanbul reuters turkish capital ankara banned...
3,Kuwait orders North Korea's ambassador to leav...,worldnews,1,kuwait reuters kuwait ordered north korea amba...
4,Sudan disappointed at renewal of U.S. travel b...,politicsNews,1,khartoum reuters sudan foreign ministry said d...
...,...,...,...,...
44893,Canada foreign minister will oppose U.S. borde...,politicsNews,1,washington reuters canada opposes idea united ...
44894,LISTEN TO THIS MEMBER OF CONGRESS WHINE ABOUT ...,politics,0,wants money find different occupation pays hey...
44895,"Republicans Rubio, Cruz release taxes, piling ...",politicsNews,1,washington reuters republican presidential can...
44896,WATCH: Fox Business Misses The Days Of Child ...,News,0,many new minimum wage increases took effect fr...
44897,OBAMA’S GAL PAL Loretta Lynch WON’T RECUSE HER...,left-news,0,reasonable americans expected never expected u...

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
vector=TfidfVectorizer()
x=vector.fit_transform(df['formatted_text'])
y=df['label']

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [33]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [34]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(13470,))

In [35]:
from sklearn.metrics import accuracy_score,recall_score
y_pred = model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9869339272457313

In [36]:
print("Recall:", recall_score(y_test, y_pred))

Recall: 0.9879200867275825

In [38]:
joblib.dump(model, 'fake_real_pkl')
joblib.dump(vector, 'vectorizer_pkl')
print("Model and vectorizer saved!")

Model and vectorizer saved!